### ISSUE TITLE
feature request: batch processing of text

### ISSUE THREAD

**Issue by junbohuang** [semantic-systems/coypu-EventExtraction#11]
The current version of EE supports only processing a single text string. The reasons are,
1. the entity linker API (wikidata) has a limited number of request
2. storage

**Comment by RicardoUsbeck** [comment]
Storage?! We should discuss that (with nicolas)

**Comment by junbohuang** [comment]
yes. it was the topic we mentioned briefly regarding processing tweet stream. There is no problem in processing batches locally.

**Comment by RicardoUsbeck** [comment]
So my take is: We build a service and if someone wants to use it, they have to take care of the scalable (distributed architecture). That is not part of this service.

**Comment by junbohuang** [comment]
yay
